version: '3.4'

services:
  progettotesi.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
  progettotesi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  progettotesi.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"